#!/bin/bash

bspc monitor LVDS1 -d "01" "02" "03" "04" "05"
bspc monitor VGA1  -d "06" "07" "08" "09" "10"

bspc config border_width  2
bspc config window_gap    12
bspc config top_padding   16

bspc config split_ratio           0.50 
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false
bspc config auto_alternate        true
bspc config auto_cancel           true

bspc config normal_border_color         "#FFFFFF"
bspc config active_border_color         "#FFFFFF"
bspc config focused_border_color        "#FFFFFF"
bspc config presel_border_color         "#FFFFFF"
bspc config urgent_border_color         "#FFFFFF"
bspc config focused_locked_border_color "#FFFFFF"
bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.1

bspc rule -a Skype pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on

. panel > /dev/null 2>&1 &
