#! /bin/sh



if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

. panel_config

CUR_X_OFFSET=0

monitors=$(bspc query -M)
for i in $monitors; do
    [ -e "$PANEL_FIFO$i" ] && rm "$PANEL_FIFO$i"
    mkfifo "$PANEL_FIFO$i"

    bspc control --subscribe |\
        grep -oE "[Mm]$i[^TM]*[TML]" --line-buffered |\
        while read line ; do echo W$line; done \
            > "$PANEL_FIFO$i" &

    barinfo > "$PANEL_FIFO$i" &

    CUR_MON_WIDTH=$(bspc query -T -m $i | grep -oE "[0-9]{2,6}" | head -n 1)
    PADDING=0
    PANEL_WIDTH=$CUR_MON_WIDTH;
    
    cat "$PANEL_FIFO$i" | panel_bar_$i |\
        lemonbar -g "$PANEL_WIDTHx30+$CUR_X_OFFSET" \
                 -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" -u 2 -f "$FONT1" -f "$FONT2" &

    CUR_X_OFFSET=$(expr $CUR_X_OFFSET + $CUR_MON_WIDTH)

done

wait
