#!/bin/sh
ffmpeg -y -f x11grab -s 1366x768 -i $DISPLAY -an $1.mkv
tput setaf 1
echo ABOUT TO MAKE WEBM FROM RECORDING, ^C TO ABORT
sleep 5
tput setaf default
ffmpeg -y -i $1.mkv -c:v libvpx -an -b:v 2000k -s 1366x768 $1.webm
